### ISSUE TITLE
O Projeto da cobrinha parou de funcionar.

### ISSUE THREAD

**Issue by AecioJose** [rafaballerini2/rafaballerini2#1]
### Opa, eu gostei muito desse projeto da cobrinha que a Rafaella Ballerini ensinou no seu perfil do Insta, porém hj em dia o cara que criou, mudou os códigos e alterou a forma de implementar no seu perfil. Eu vasculhando o perfil e o projeto dele descobri a nova forma de implementar a cobrinha no seu readme

Quem quiser acessar os códigos diretamente do criador é esse link:  https://github.com/Platane/Platane/tree/master

## 1º  - No seu readme mudou a forma de chamar a animação, no lugar de **YourUser**  troque para o nome do seu perfil
```
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/YourUser/YourUser/output/github-contribution-grid-snake-dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/YourUser/YourUser/output/github-contribution-grid-snake.svg">
  <img alt="github contribution grid snake animation" src="https://raw.githubusercontent.com/YourUser/YourUser/output/github-contribution-grid-snake.svg">
</picture>
```

## 2º - No projeto anterior vc tinha que copiar o código e alterar o nome de usuário, agr você não precisa mudar nada no código cobrinha.yml
(eu renomiei o meu arquivo para(main.yml) que o msm que o do platane(criador), não funciona com outros nomes, tem que ser main.yml)
## lembre-se de está no diretorio "NomeDoSeuUsuario/.github/workflows/cobrinha.yml<br>(ou o nome que preferir eu escolhi main.yml)"
**o código que tem que está la dentro é esse abaixo**
``` 
name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    
  

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
          
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

## Se quiser conferir no meu perfil 🙃 https://github.com/AecioJose
